[package]
name = "ephemeral-token-program"
version = "0.0.0"
description = "Ephemeral SPL Token program"
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = "./README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
logging = ["ephemeral-spl-api/logging"]
no-fees = ["ephemeral-spl-api/no-fees"]

[dependencies]
bytemuck = { workspace = true }
const-crypto = { workspace = true }
ephemeral-rollups-pinocchio = { workspace = true }
ephemeral-spl-api = { path = "../e-token-api" }
hydra-api = { workspace = true }
magicblock-delegation-program-api = { workspace = true, default-features = false, features = [
    "cpi",
] }
pinocchio = { workspace = true }
pinocchio-log = { workspace = true }
pinocchio-system = { workspace = true }
pinocchio-token-2022 = { workspace = true }
pinocchio-associated-token-account = { workspace = true }
solana-instruction = { workspace = true }
solana-address = { workspace = true }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
spl-token-interface = { workspace = true }
static_assertions = { workspace = true }
wheels = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true }
solana-program-pack = { workspace = true }
solana-keypair = { workspace = true }
solana-program = { workspace = true }
solana-program-test = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { workspace = true }
solana-system-interface = { workspace = true }
solana-account = { workspace = true }
spl-token-interface = { workspace = true }
magicblock-delegation-program-api = { workspace = true, default-features = true }
#magicblock-magic-program-api = "=0.8.7"
magicblock-magic-program-api = { git = "https://github.com/magicblock-labs/magicblock-validator.git", rev = "81840b66189f50ab321259cc8e3c19e187126010" }
bincode = "1.3.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fslock = "0.2"
serial_test = "3.4.0"

[lints]
workspace = true
