app = "ephemeral-spl-token-api"
primary_region = "sin"

[build]
dockerfile = "Dockerfile"

[env]
EPHEMERAL_ENDPOINT_URL = "https://rpc.magicblock.app/mainnet"
EPHEMERAL_TEE_ENDPOINT_URL = "https://tee.magicblock.app"

[[services]]
internal_port = 4000
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
type = "requests"
hard_limit = 1000
soft_limit = 800

[services.http_options]
compress = "gzip"

[services.http_checks]
enabled = true
interval = 10000
timeout = 5000
grace_period = "5s"
method = "GET"
path = "/"
protocol = "http"
tls_skip_verify = false

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[services.tcp_checks]]
interval = "10s"
timeout = "5s"
